### ISSUE TITLE
not works on iOS 8.4

### ISSUE THREAD

**Issue by gaoryrt** [Qquanwei/n2c#1]
Awesome repo but not works on iOS 8.4

**Comment by Qquanwei** [comment]
你好，可以把报错信息反馈一下吗，或者提供一个最小发生环境？

**Comment by gaoryrt** [comment]
Sorry about that, and here're something might help.

test code:
![image](https://user-images.githubusercontent.com/5306513/41282300-577dc9a2-6e66-11e8-8724-fe1f26c6c907.png)

expected log (macOS 10.13 Chrome V66):
![image](https://user-images.githubusercontent.com/5306513/41282426-9af57c70-6e66-11e8-8ba0-617a3bc5321c.png)

not work (iOS 8.4 Safari):
![image](https://user-images.githubusercontent.com/5306513/41283086-401b633a-6e68-11e8-9db0-fde2bfd0aa69.png)
says `TypeError: Requested keys of a value that is not an object.`

**Comment by Qquanwei** [comment]
fixed: n2c@1.0.15
